### ISSUE TITLE
Week 3- strings

### ISSUE THREAD

**Issue by mxistrissongpanya-matc** [madisoncollege-it-programs/python-scripting-mxistrissongpanya-matc#3]
Hello, my assignment for week 3 lab( formatting strings) is ready to be graded. Thank you.

**Comment by cethenmc** [comment]
This one is also not executable at the command line.  All of these have an issue executing from the command line.  Most of the problem, I bet, lies in your first line of the script.  Look very carefully at it.  Before you push your code to Git Hub, you should navigate to the directory of your script and make sure you can run it by entering...

./strings.py

This will likely error for you, too.  However, it may give you the clue to know what is wrong.  Please book me if you need help.

Thanks.

Chris

**Comment by cethenmc** [comment]
Hi, Max.  Thanks for making this executable.  This assignment was very specific in that the lines had to match exactly to what was printed.  There are 7 of the 14 that are not accurate.  I will record 4.5 out of 8 possible points in the grade book now.  However, I encourage you to resubmit this assignment.

#3,6,7,14 do not have the correct capitalization.
#9 does not go to the correct decimal place
#12 is not spaced between the brackets ("] [") correctly.
#13 is missing

Please correct, resubmit to Git Hub, and reply to this post when ready.

**Comment by cethenmc** [comment]
I will give you until Friday on this one.  Otherwise, you will lock in the 4.5 out of 8 that I have recorded.

**Comment by cethenmc** [comment]
Locked in this grade for the lab.
