### ISSUE TITLE
Week 6

### ISSUE THREAD

**Issue by mxistrissongpanya-matc** [madisoncollege-it-programs/python-scripting-mxistrissongpanya-matc#6]
Ready for grading. I hope you like my modified script : )

**Comment by cethenmc** [comment]
boolean.py = 8 out of 8
flowControl.py = No comment if you choose a door other than 1, 2, or 3.   Same after choosing door 2:  if you choose a door other than left, right or turn around, you just fall out of the game.  Your 3rd door does nothing except tell you that you won a brand new car, but there was no door underneath.  6 out of 8.  Can complete for full credit this week.
